# DO NOT CHANGE THE NAME (edemand_partner),
#IF YOU WANT TO CHANGE THE APP NAME THEN YOU HAVE TO CHANGE THE EACH IMPORT STATEMENT IN THE CODE
#THIS NAME WILL NOT IMPACT IN YOUR APP, SO ITS NOT MANDATORY TO CHANGE IT
name: edemand_partner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.5.0+49

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  flutter_svg: ^2.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  #rive: ^0.13.20
  lottie: ^3.3.2
  readmore: ^3.0.0
  flutter_slidable: ^4.0.3
  easy_stepper: ^0.9.1
  toastification: ^3.0.3

  # State Management
  flutter_bloc: ^9.1.1
  # bloc: ^9.0.0

  # Firebase Services
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_auth: ^6.1.0
  firebase_analytics: ^12.0.4
  clarity_flutter: ^1.5.0

  # Networking & API
  dio: ^5.9.0
  http_parser: ^4.1.2
  any_link_preview: ^3.0.3

  # Local Storage & Data
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  # hive: ^2.2.3
  # shared_preferences: ^2.5.1

  # Media & File Handling
  image_picker: ^1.2.0
  file_picker: ^10.3.0
  video_player: ^2.10.0
  mime: ^2.0.0
  path: ^1.9.1
  open_file: ^3.5.10

  # Maps & Location
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  # path_drawing: ^1.0.1

  # Charts & Analytics
  fl_chart: ^1.1.1

  # Payment & E-commerce
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^12.0.2

  # Web & HTML
  webview_flutter: ^4.13.0
  html_editor_enhanced: ^2.7.1
  flutter_widget_from_html: ^0.17.1

  # Utilities
  intl: ^0.20.2
  version: ^3.0.2
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.1
  pinput: ^5.0.2
  quick_actions: ^1.1.0
  awesome_notifications: ^0.10.1
  share_plus: ^12.0.0
  google_mobile_ads: ^6.0.0
  vibration: ^3.1.4
  flutter_localization: ^0.3.3
  path_provider: ^2.1.5

  # cupertino_icons: ^1.0.2


dependency_overrides:
  sqflite_android: 2.4.1
  #intl: ^0.17.0
  #webview_flutter_android: 4.0.1 #3.16.1
  #flutter_inappwebview_ios:
    #git:
      #url: https://github.com/IncM/flutter_inappwebview
      #path: flutter_inappwebview_ios
      #ref: cbc214c7b2cf5fd7996ff2e9e25d203946b74bc3

dev_dependencies:
  rename: ^3.0.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_logo_icon.png"
  adaptive_icon_foreground: "assets/icons/forground.png"
  adaptive_icon_background: "assets/icons/background.png"
  remove_alpha_ios: true
  # background_color_ios: "#FFC100"

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/languages/
    - assets/mapTheme/
    - assets/animation/
    - assets/images/flags/
    - assets/images/svg/branding/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
